### ISSUE TITLE
Obsolete SSL version in scdissector.org

### ISSUE THREAD

**Issue by BoydSteere** [effiken/scDissector#2]
Hi, Kenigsberg lab coders:

When I click on the link for (https://scdissector.org/martin), I get the following warning from my browser (whether using Chrome or Edge).  You might want to consider upgrading it to TLS 1.2 to keep it accessible in the future.  Thanks for your helpful app!

Your connection is not fully secure
This site uses an outdated security configuration, which may expose your information (for example, passwords, messages, or credit cards) when it is sent to this site.

NET::ERR_SSL_OBSOLETE_VERSION

Back to safety Hide advanced

The connection used to load this site used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading this site. The server should enable TLS 1.2 or later.

Proceed to scdissector.org (unsafe)

 

Cheers,
Boyd Steere
Principal Research Scientist
Lilly Immunology

**Comment by effiken** [comment]
Hi Boyd,

Thank you for letting us know! We will fix it as soon as possible.

Best,
Effi

**Comment by effiken** [comment]
Done!
