### ISSUE TITLE
Possibility of Downloading data

### ISSUE THREAD

**Issue by saeedfc** [effiken/scDissector#3]
Hi,

Is it possible to download the data (or meta data) from scDissector? I was working on annotating T cell data. The data displayed [here](https://scdissector.org/martin) and published in [Martin et al. Cell 2019](https://www.sciencedirect.com/science/article/pii/S0092867419308967#MMC2) has one of the most detailed annotation of T cells but unfortunately not included in the GSE deposit.

**Comment by effiken** [comment]
Hi, thank you for your interest in the study. The full annotation information can be downloaded from:
https://kenigsberg-group.org/resources/

Please let us know if something is missing.

**Comment by saeedfc** [comment]
That's great.

Thanks a lot.
Kind regards,
Saeed
